Branch
huiyeongyoon/newmall pull request #3
Opened 2021-09-27 04:28 UTC by huiyeongyoon

자바스크립트 추가를 위한 html class명 수정 및 자바스크립트 추가 (로그인 기능, 정규식,모달창 생성, esc눌를떄 click시 모달창 꺼짐

2021-09-29 12:38 UTC, wallababa requested changes
일단 첫 리뷰 작성했습니다. 더 작성하려고 했는데 아마 다른 페이지도 비슷한 수정을 해야하지 않을까 싶습니다. 전체적인 리뷰를 적겠습니다.

1. 포트폴리오용으로 만드시는 걸로 알고 있는데 만드신 걸 오늘 확인해보니 다른 선택지는 없을 것 같습니다. bootstrap 사용해주세요. 가져다 사용해도 되고 스타일만 베껴서 써도 됩니다. 검토하는 사람도 사람인지라 좋지 못한 UI/UX는 부정적인 영향을 미칩니다.

2. 처음엔 자바스크립트와 관련해서 생각보다 괜찮다는 생각이 들었지만 개발해야하는 범위가 늘어나니 부족함이 드러나는 것 같습니다. 자바스크립트 교재를 선택해서 공부해주시고 어떤 책으로 공부하시는지 알려주세요. 매주 면접 형식으로 질문하고 답하는 시간을 갖겠습니다.

3. 항상 지금 하시는게 업무고 사수인 제가 검토하는 거라고 생각해주세요. 그말인즉, 요청된 기본적인 내용은 다음엔 최대한 발생해선 안 됩니다. 예를 들어, 통일된 코드 스타일, 빈 여백 등과 같은 내용은 항상 체크해주세요.

오늘 올려드린 리뷰 내용 수정하시고 카톡으로 연락주세요 !

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> +//중요 왜 modal 하면 안되는데 modal-overlay-fail 하면 됨?
문제가 뭔지 알 수 없습니다. 위에 언급한 것 처럼 PR 설명에 자세하게 적어주세요

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> +
어딘 함수 내부의 첫 줄을 붙이고 어딘 지금 여기처럼 띄워놨는데 전부 붙여주세요. 그리고 잘못 작성된 것이든 아니든 통일성있게 코드를 작성해주세요.

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> +  const reg = /^[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/i;
이메일 validation check를 위한 정규표현식인 것 같은데 변수명이 적절하지 않습니다. 변수명을 수정해주세요.

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> +  const regExp = /^(?=.*\d)(?=.*[a-zA-Z])[0-9a-zA-Z]{8,20}$/; //  8 ~ 20자 영문, 숫자 조합
이메일 유효성 검증 정규표현식은 `reg`로 이름을 지었는데 왜 여긴 `regExp`인가요. 잘못된 것이든 잘된 것이든 통일해주세요.

소프트웨어의 가장 중요한 원칙 중 하나는 여럿이 개발해도 한 사람이 개발한 것처럼 보여야한다는 것입니다.
혼자 작성하셨는데 통일성이 없으면 안 됩니다.

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> + modalOff = () => {
함수인데 동사로 시작하지 않네요.

`hideModal`이 더 적절할 것 같습니다.

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> +    $modalSuccess.style.display = 'flex';
지금 적용하신 방식은 페이지에서 발생할 수 있는 모든 모달을 미리 HTML에 랜더링해놓고 필요할 때 스타일을 통해 보여주는 방식이네요.
하지만 적절하지 않은 방법입니다. 만약

1. 많은 종류의 모달이 사용된다면 전부 미리 랜더링 해놓고 껐다 켰다 하거나
2. 모달 내부에 여러 값을 받아 사용하는 경우 열고 닫을 때마다 데이터 관리를 해줘야
하는 등 문제가 많습니다.

모달이 필요해지면 그 때 모달을 만들어서 랜더링 해주고 필요 없어지면 모달을 페이지에서 지우는 방법으로 수정해주세요.

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> +const $email = document.querySelector('.email');
문자열을 작성하실 때 어딘 `'...'`와 같이 single quote를 사용하시고 어딘 `"..."`와 같이 double quote를 사용하시는데 통일해주세요.

2021-09-29 12:38 UTC, wallababa commented on javascript/sign_in1.js
> +  event.preventDefault();
form 요소는 이렇게 사용하지 않고 다음과 같이 사용합니다.

```javascript
const $form = document.querySelector('form'); // form 요소에 별도의 선택자가 있다면 더 좋습니다.

$form.addEventListener('submit', (event) => {
  event.preventDefault();
  const formData = new FormData(event.target);

  console.log('form data : ', formData.get('email'), formData.get('password'));
});
```

이렇게 사용하려면 email input 요소와 password input 요소에 각각 `name` 속성이 있어야 합니다.
```html
<div class="email-box">
  <label for="email">아이디</label>
  <input type="email" class="email" id="email" name="email">
</div>
<div class="password-box">
  <label for="password">비밀번호</label>
  <input type="password" class="password" id="password" name="password">
</div>
```

[참고 문서](https://developer.mozilla.org/ko/docs/Web/API/FormData/FormData)

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +        <div class="close-area">X</div>
닫기 버튼이면 `<button>` 요소를 사용해주세요.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +        <div class="email-box">
`box`라는 키워드를 주로 사용하시는 것 같은데 개발자 입장에서 볼 땐 아무런 의미도 없는 키워드 인것 같습니다.
아무런 의미 없이 단순히 스타일을 위해서 싸주는 용도라면 `wrapper`가 더 적절합니다.

지난번 주석에 적어놨었는데 다시 적어놓겠습니다.
`main`, `section`, `h1~h6`, `header`, `footer`, `aside`, `dialog` 요소에 대해 알아봐주세요.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +      <a class="non-sign-up"href="">비회원 주문조회</a>
`non-sign-up`은 적절하지 않은 것 같습니다. `nonmember-order`와 같이 `order`라는 이름이 들어가야 합니다.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +          <li><a href="">비밀번호 찾기</a></li>
`아이디찾기`에선 띄어쓰기가 없는데 `비밀번호 찾기`에선 띄어쓰기가 있네요. 통일해주시면 좋을 것 같습니다.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +      width: 20%;
모달의 `width`와 `height`가 `%` 기준이라면 모바일 같이 작은 화면에선 너무 작아져서 안 됩니다. 최소 너비와 최대 너비를 활용해서 설정해야 합니다.

```css
/* 예시 */
min-width: 200px;
min-height: 300px;
max-width: 90%;
max-height: 90%;
``

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +      justify-content: flex-end;
같은 속성의 스타일은 같이 묶어주세요.
```css
display: flex;
justify-content: flex-end;
padding-right: 10%;
width: 100%;
...
```

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +    .modal.modal-overlay-fail {
`modal-overlay-success`, `modal-overlay-fail` class 속성을 갖는데 `modal` 클래스가 없는 경우가 없다면 앞에 붙여놓은 `.modal`은 의미 없습니다. 제거하는게 좋을 거 같습니다.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +
빈 공간 제거해주세요.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +      background: rgba( 69, 139, 197, 0.70 );
위에선 `rgba(`와 같이 괄호 앞에 빈 공간이 없는데 이 선택자 스타일에선 모두 내용의 앞 뒤로 빈 공간이 있네요. 빈공간 없애는 방향으로 통일해주세요.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +<html lang="en">
`<html lang="ko">`로 수정해주세요.

2021-09-29 12:38 UTC, wallababa commented on html/sign_in1.html
> +  <style>
다른 스타일은 css에 넣고 왜 이 스타일은 `<style>` 요소에 넣으셨나요?

2021-09-29 15:54 UTC, merged

2021-09-30 00:54 UTC, huiyeongyoon reviewed
html css 리뷰 수정사항

2021-09-30 00:54 UTC, huiyeongyoon commented on html/sign_in1.html
> +  <main id="main">
y축으로 스크롤 된다가 무슨 뜻인가요? 어떻게  확인해보면 될까요?

2021-09-30 00:54 UTC, huiyeongyoon commented on html/sign_in1.html
> +      <div>
ul태그가 block인걸 깜박했습니다.

2021-09-30 00:54 UTC, huiyeongyoon commented on html/sign_in1.html
> +      width: 20%;
max-width: 90%;,
max-height: 90%
주는건 모바일에서 거의 가장 큰 화면으로 보여줄려고 하는건가요?;

2021-09-30 00:54 UTC, huiyeongyoon commented on html/sign_in1.html
> +        <div class="email-box">
header: 문서의 가장 윗부분: 로고 제목 검색 버튼
footer: 문서의 가장 아랫부분: 작성자 저작권 관련된 문서 등
main: 한 문서에는 한 개의 메인 만 사용 가능
section: 문서의 한 구획을 잡을때 사용 ex: wrapper를 div 대신 sectiion으로 사용 가능
aside: 문서 외 별도 컨텐츠 메인 컨텐츠와 별개인 것 에 사용함
dialog: 팝업창 닫을 수 있는 상자

2021-09-30 00:54 UTC, huiyeongyoon commented on html/sign_in1.html
> +        <ul class="bottom-box">
ul 태그위에 div를 넣고 마진을 줘서 띄워줄려고 한거 같습니다..... ul태그가 왼쪽으로 쏠려있다는게 무슨 뜻 인가요?

2021-09-30 16:33 UTC, huiyeongyoon commented on javascript/sign_in1.js
> +//중요 왜 modal 하면 안되는데 modal-overlay-fail 하면 됨?
선택자를 queryselector로 가져올때 modal을 가져오면 해당 엘리먼트가 선택이 되야될꺼 같은데 안되서 적어 놨습니다.

2021-09-30 16:59 UTC, huiyeongyoon reviewed
확인 하였습니다